language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=xml_models setup.py test
cache: pip
after_success:
  coveralls
